import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// layout.tsx : 자기랑 같은 레벨에 있는 페이지와 그 아래 경로에 있는 페이지,레이아웃을 감싸주는 역할

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>이것이 헤더다</header>
        {children}
      </body>
      <footer>이것이 푸터다</footer>
    </html>
  );
}
